/**
 * CLAUDE.md agent-onboarding doc renderer.
 *
 * Produces a per-solution markdown file that auto-loads into Claude Code
 * sessions when the developer clones the solution repo. Closes the gap where
 * a fresh agent has no idea how to iterate, which tools to use, or what
 * pitfalls to avoid.
 *
 * Structure:
 *   - Auto-generated header (above SENTINEL) — rewritten on every regen
 *   - SENTINEL line — marks the boundary
 *   - Solution-specific notes (below SENTINEL) — preserved across regens
 *
 * Callers:
 *   - ateam_write_agent_doc({ solution_id, overwrite? }) — explicit backfill
 *   - ateam_build_and_run — auto-invoked post-deploy (non-fatal)
 */

export const AGENT_DOC_SENTINEL = "<!-- SOLUTION-SPECIFIC NOTES BELOW — not auto-regenerated -->";

/**
 * Render the auto-generated section of CLAUDE.md.
 *
 * @param {object} params
 * @param {object} params.solution    - Full solution definition
 * @param {Array}  params.skills      - Array of skill definitions
 * @param {Array}  [params.connectors] - Solution-connector metadata
 * @returns {string} markdown
 */
export function renderAgentDocHeader({ solution, skills = [], connectors = [] }) {
  const solId = solution?.id || "unknown";
  const solName = solution?.name || solId;
  const solDesc = solution?.description || "";
  const orchestratorId = solution?.orchestrator_skill || null;
  const tenantHint = inferTenantFromId(solId);

  const skillsList = skills.map((s) => {
    const role = s.role || (s.id === orchestratorId ? "orchestrator" : "worker");
    const desc = s.description || s.problem?.statement || "";
    return `- **${s.id}** _(${role})_ — ${oneLine(desc)}`;
  }).join("\n") || "_(no skills defined)_";

  const platformConnectorIds = (solution?.platform_connectors || []).map((c) => c.id);
  const solutionConnectorIds = [
    ...new Set(connectors.map((c) => c.id).filter(Boolean)),
  ];
  const connectorTable = buildConnectorTable({
    platform: platformConnectorIds,
    solution: solutionConnectorIds,
  });

  const uiPlugins = (solution?.ui_plugins || []).map((p) => {
    const mode = p.render?.mode || "?";
    return `- **${p.name || p.id}** (\`${p.id}\`, ${mode})`;
  }).join("\n") || "_(none)_";

  const tools = buildToolTable();
  const pitfalls = buildUniversalPitfalls();
  const repoLayout = buildRepoLayout({ skills, connectors });

  return `# ${solName} — Agent Onboarding

> This file is auto-generated by A-Team on every deploy.
> Everything ABOVE the sentinel line is regenerated.
> Solution-specific notes go BELOW the sentinel — they are preserved.

You are working on A-Team solution **${solId}**. Read this entire file before your first tool call.

---

## 1. What this solution is

${solDesc || "_(no description set — add one to solution.json)_"}

${tenantHint ? `- **Tenant:** \`${tenantHint}\`` : ""}
- **Orchestrator skill:** ${orchestratorId ? `\`${orchestratorId}\`` : "_(none set)_"}

---

## 2. Skills

${skillsList}

---

## 3. Connectors

${connectorTable}

---

## 4. UI plugins

${uiPlugins}

---

## 5. Repo layout

\`\`\`
${repoLayout}
\`\`\`

---

## 6. Dev workflow (single-branch, GitHub-first)

Everything lands on \`main\` directly. Checkpoints via \`safe-*\` tags.

\`\`\`
1. git clone <this repo>
2. edit code in your IDE / agent
3. git commit && git push origin main
4. ateam_build_and_run(solution_id: "${solId}", github: true)
5. ateam_test_skill / ateam_test_connector  — verify
6. ateam_github_promote(solution_id)          — checkpoint when green
\`\`\`

Or edit remotely via \`ateam_github_patch\` / \`ateam_github_write\` — same effect.

**First tool call every session:** \`ateam_auth(api_key: "adas_${tenantHint || "<tenant>"}_<hex>")\`.

---

## 7. Which MCP tool for what

${tools}

**Rule:** prefer \`ateam_patch\` over \`ateam_github_patch\` + \`ateam_build_and_run\` when changing skill definitions — it's one call and always redeploys.

---

## 8. Universal pitfalls (apply to every A-Team solution)

${pitfalls}

---

## 9. Spec & examples

- \`ateam_get_spec(topic: "skill")\` — full skill schema
- \`ateam_get_spec(topic: "solution")\` — solution schema
- \`ateam_get_examples(type: "skill" | "connector" | "connector-ui" | "solution")\`
- \`ateam_get_workflows()\` — builder workflow state machines

Read these on your first edit into an area you haven't touched.

---

${AGENT_DOC_SENTINEL}

`;
}

/**
 * Merge the newly-rendered header with an existing CLAUDE.md, preserving
 * anything below the sentinel (solution-specific notes).
 *
 * @param {string} freshHeader   - Output of renderAgentDocHeader
 * @param {string|null} existing - Current CLAUDE.md contents (or null if new file)
 * @returns {string} merged markdown
 */
export function mergeAgentDoc(freshHeader, existing) {
  if (!existing) return freshHeader;
  const idx = existing.indexOf(AGENT_DOC_SENTINEL);
  if (idx === -1) {
    // Existing file has no sentinel — treat the whole file as manual notes,
    // prepend the auto-generated header, separate by sentinel.
    return freshHeader + "\n" + existing.trimStart();
  }
  const tail = existing.slice(idx + AGENT_DOC_SENTINEL.length);
  return freshHeader + tail;
}

// ──────────────────────────────────────────────────────────────────────────

function oneLine(s) {
  return String(s || "").replace(/\s+/g, " ").trim().slice(0, 200);
}

function inferTenantFromId() {
  // Can't reliably infer from solution_id alone; caller can override by
  // setting tenant on the rendered header via post-processing if needed.
  return null;
}

function buildConnectorTable({ platform, solution }) {
  const rows = [];
  if (solution.length) {
    rows.push("**Solution connectors** (live in this repo under `connectors/`):");
    for (const id of solution) rows.push(`  - \`${id}\``);
    rows.push("");
  }
  if (platform.length) {
    rows.push("**Platform connectors** (shared infrastructure, not in this repo):");
    for (const id of platform) rows.push(`  - \`${id}\``);
    rows.push("");
  }
  if (!rows.length) rows.push("_(no connectors declared)_");
  return rows.join("\n");
}

function buildToolTable() {
  return [
    "| Task | Tool |",
    "|------|------|",
    "| Edit connector source code | `ateam_github_patch` / `ateam_github_write` → `ateam_build_and_run(github:true)` |",
    "| Edit skill definition (persona, tools, intents, guardrails) | `ateam_patch(target:\"skill\", skill_id, updates)` |",
    "| Edit solution definition | `ateam_patch(target:\"solution\", updates)` |",
    "| First deploy / redeploy from GitHub | `ateam_build_and_run(github:true)` |",
    "| Run a skill end-to-end | `ateam_test_skill(solution_id, skill_id, message)` |",
    "| Call one connector tool in isolation | `ateam_test_connector(solution_id, connector_id, tool, args)` |",
    "| Inspect deployed state | `ateam_get_solution(solution_id, view: \"definition\"|\"skills\"|\"health\")` |",
    "| Read file from repo | `ateam_github_read(solution_id, path)` |",
    "| Checkpoint | `ateam_github_promote(solution_id, label)` |",
    "| Rollback | `ateam_github_rollback(solution_id, tag)` |",
    "| List checkpoints | `ateam_github_list_versions(solution_id)` |",
  ].join("\n");
}

function buildUniversalPitfalls() {
  return [
    "- **`ateam_test_connector` runs as `_system_service`.** Core strips user-provided `_adas_actor` when you call via the test harness. Use it for connector-level bugs; use `ateam_test_skill` / `ateam_conversation` for per-user-actor flows.",
    "- **`.ateam/export.json` is auto-generated.** Never hand-edit. Deploys read it, so stale copies silently break things.",
    "- **Prefer `ateam_patch` over `github_patch` + `build_and_run`** for skill-definition edits. One call, guaranteed redeploy, no drift.",
    "- **Always refetch dynamic ids.** Corpus ids, job ids, actor ids change. Call `docs.corpus.list` / `ateam_list_solutions` / etc. in the current job — don't reuse ids from memory or previous sessions.",
    "- **MCP tool param names are strict.** `top_k` (not `k`), `corpus_id` (not `corpus`). Passing wrong names silently fails zod validation.",
    "- **Don't count `{ok:false}` as success.** When calling one MCP from another, always check `result.ok` before incrementing a success counter.",
    "- **Connectors are stdio, not HTTP.** Use `StdioServerTransport`. Never `app.listen()`. Log with `console.error` (stdout is the JSON-RPC channel).",
    "- **Shared-tenant resources need `shared: true`.** When a resource (corpus, bind, etc.) is used across users in a tenant, pass `shared: true` at create time — otherwise per-user actor isolation blocks cross-user access.",
  ].map((s) => "- " + s.replace(/^- /, "")).join("\n");
}

function buildRepoLayout({ skills, connectors }) {
  const skillDirs = skills.map((s) => `  ${s.id}/skill.json`).join("\n") || "  _(no skills)_";
  const connDirs = connectors.length
    ? connectors.map((c) => `  ${c.id}/\n    server.js\n    package.json`).join("\n")
    : "  _(no solution connectors)_";
  return [
    "solution.json                    # full solution definition",
    "skills/",
    skillDirs,
    "connectors/                      # solution connectors (stdio MCPs)",
    connDirs,
    ".ateam/export.json               # auto-generated deploy bundle (don't hand-edit)",
    "CLAUDE.md                        # this file — auto-regenerated above sentinel",
  ].join("\n");
}
