/**
 * CLAUDE.md agent-onboarding doc renderer.
 *
 * Produces a per-solution markdown file that auto-loads into Claude Code
 * sessions when the developer clones the solution repo. Closes the gap where
 * a fresh agent has no idea how to iterate, which tools to use, or what
 * pitfalls to avoid.
 *
 * Structure:
 *   - Auto-generated header (above SENTINEL) — rewritten on every regen
 *   - SENTINEL line — marks the boundary
 *   - Solution-specific notes (below SENTINEL) — preserved across regens
 *
 * Callers:
 *   - ateam_write_agent_doc({ solution_id, overwrite? }) — explicit backfill
 *   - ateam_build_and_run — auto-invoked post-deploy (non-fatal)
 */

import { BRANCH_WORKFLOW } from './branchWorkflow.js';

export const AGENT_DOC_SENTINEL = "<!-- SOLUTION-SPECIFIC NOTES BELOW — not auto-regenerated -->";

/**
 * Render the auto-generated section of CLAUDE.md.
 *
 * @param {object} params
 * @param {object} params.solution    - Full solution definition
 * @param {Array}  params.skills      - Array of skill definitions
 * @param {Array}  [params.connectors] - Solution-connector metadata
 * @returns {string} markdown
 */
export function renderAgentDocHeader({ solution, skills = [], connectors = [] }) {
  const solId = solution?.id || "unknown";
  const solName = solution?.name || solId;
  const solDesc = solution?.description || "";
  const orchestratorId = solution?.orchestrator_skill || null;
  const tenantHint = inferTenantFromId(solId);

  const skillsList = skills.map((s) => {
    const role = s.role || (s.id === orchestratorId ? "orchestrator" : "worker");
    const desc = s.description || s.problem?.statement || "";
    return `- **${s.id}** _(${role})_ — ${oneLine(desc)}`;
  }).join("\n") || "_(no skills defined)_";

  // Classify connectors by the `source` field on solution.platform_connectors[].
  // Default "platform" for back-compat with older solutions that don't set it.
  // Solution-owned connectors (source:"solution") have source code in
  // connectors/<id>/ inside the repo. See skill-validator schema for the
  // platform_connectors[i].source field. The previous classifier put EVERY
  // platform_connectors entry into the "platform" bucket regardless of
  // ownership, which misclassified solution-owned connectors and bit ada
  // on 2026-05-15.
  const pcs = solution?.platform_connectors || [];
  const platformConnectorIds = pcs
    .filter((c) => (c.source || "platform") === "platform")
    .map((c) => c.id);
  const solutionConnectorIds = [
    ...new Set([
      // Anything explicitly marked source:"solution"
      ...pcs.filter((c) => c.source === "solution").map((c) => c.id),
      // Plus anything in the separately-passed connectors list (live runtime
      // discovery) that isn't already accounted for as platform.
      ...connectors.map((c) => c.id).filter(Boolean),
    ]),
  ].filter((id) => !platformConnectorIds.includes(id));
  const connectorTable = buildConnectorTable({
    platform: platformConnectorIds,
    solution: solutionConnectorIds,
  });

  const uiPlugins = (solution?.ui_plugins || []).map((p) => {
    const mode = p.render?.mode || "?";
    return `- **${p.name || p.id}** (\`${p.id}\`, ${mode})`;
  }).join("\n") || "_(none)_";

  const tools = buildToolTable();
  const pitfalls = buildUniversalPitfalls();
  const repoLayout = buildRepoLayout({ skills, connectors });

  return `# ${solName} — Agent Onboarding

> This file is auto-generated by A-Team on every deploy.
> Everything ABOVE the sentinel line is regenerated.
> Solution-specific notes go BELOW the sentinel — they are preserved.

You are working on A-Team solution **${solId}**. Read this entire file before your first tool call.

---

## 1. What this solution is

${solDesc || "_(no description set — add one to solution.json)_"}

${tenantHint ? `- **Tenant:** \`${tenantHint}\`` : ""}
- **Orchestrator skill:** ${orchestratorId ? `\`${orchestratorId}\`` : "_(none set)_"}

---

## 2. Skills

${skillsList}

---

## 3. Connectors

${connectorTable}

---

## 4. UI plugins

${uiPlugins}

---

## 5. Repo layout

\`\`\`
${repoLayout}
\`\`\`

---

## 6. Dev workflow (two branches — \`${BRANCH_WORKFLOW.write_branch}\` then \`${BRANCH_WORKFLOW.deploy_branch}\`)

${BRANCH_WORKFLOW.one_line}

${BRANCH_WORKFLOW.write_side}

> \`${BRANCH_WORKFLOW.write_branch}\` may not exist yet in this repo. The platform creates it from
> \`${BRANCH_WORKFLOW.deploy_branch}\` on the first write it makes (ensureDevBranch), so a repo that has
> only ever been written to by hand will not have it until then — hence the
> \`|| git checkout -b\` on the clone line under "Editing files by hand" below.

${BRANCH_WORKFLOW.deploy_side}

### Iterate — deploy and TEST without promoting

${BRANCH_WORKFLOW.iterate_note}

\`\`\`
${BRANCH_WORKFLOW.iterate_without_promote.map((l) => l.replace(/solution_id(?=[,)])/, `solution_id: "${solId}"`)).join("\n")}
\`\`\`

### Ship — when it is right

\`\`\`
1. ${BRANCH_WORKFLOW.promote_tool}(solution_id: "${solId}", dry_run: true)   — see exactly what would ship
2. ${BRANCH_WORKFLOW.promote_tool}(solution_id: "${solId}")                  — merges ${BRANCH_WORKFLOW.write_branch} → ${BRANCH_WORKFLOW.deploy_branch}, tags ${BRANCH_WORKFLOW.tag_format}
3. ateam_build_and_run(solution_id: "${solId}")                   — deploys \`${BRANCH_WORKFLOW.deploy_branch}\`
\`\`\`

Editing files by hand instead of via the tools:

\`\`\`
git clone <this repo> && git checkout ${BRANCH_WORKFLOW.write_branch} 2>/dev/null || git checkout -b ${BRANCH_WORKFLOW.write_branch}
# edit, then:
git commit && git push origin ${BRANCH_WORKFLOW.write_branch}
\`\`\`

**${BRANCH_WORKFLOW.the_silent_mistake}**

Or edit remotely via \`ateam_github_patch\` / \`ateam_github_write\` — same branch. Either way the
next iterate deploy (\`ateam_redeploy\`, \`ateam_patch\`, \`ateam_upload_connector\`) picks the change
up from \`${BRANCH_WORKFLOW.write_branch}\`: the tools also copy it into the Builder at once, and a hand push is
pulled in by the pre-deploy check — unless the Builder's copy of that same file also changed since the two
last agreed (a Builder save that never reached GitHub), or holds main content \`${BRANCH_WORKFLOW.write_branch}\` lacks (a hotfix
or rollback a build_and_run deployed). Then the tools leave the Builder's copy alone, and \`ateam_redeploy\` and
\`ateam_patch\` refuse to deploy the solution — any skill of it, not only that file's — and name the file instead of
picking a side. (\`ateam_upload_connector\` reads \`${BRANCH_WORKFLOW.write_branch}\` directly and has no such check.)
A Builder save that did not reach \`${BRANCH_WORKFLOW.write_branch}\` (held for that reason, or its push failed) stays in the
Builder and its reply says so (NOT_WRITTEN_TO_GITHUB); until it is placed, \`ateam_build_and_run\` is refused
(UNPUSHED_BUILDER_CHANGE) rather than overwrite it, and so is \`ateam_github_pull\`. \`ateam_redeploy(solution_id)\` writes
it to \`${BRANCH_WORKFLOW.write_branch}\` (solution.json and every skill); \`ateam_github_pull(solution_id, discard_builder_changes: true)\`
drops it for \`${BRANCH_WORKFLOW.write_branch}\`'s copy.

**First tool call every session:** \`ateam_auth(api_key: "adas_${tenantHint || "<tenant>"}_<hex>")\`.

---

## 7. Which MCP tool for what

${tools}

**Rule:** prefer \`ateam_patch\` over \`ateam_github_patch\` + a deploy when changing skill definitions — it's one call, and it redeploys what it patched. Read its \`redeploy\` phase: a redeploy that failed is reported there, and the edit is kept either way.

---

## 8. Universal pitfalls (apply to every A-Team solution)

${pitfalls}

---

## 9. Spec & examples

- \`ateam_get_spec(topic: "skill")\` — full skill schema
- \`ateam_get_spec(topic: "solution")\` — solution schema
- \`ateam_get_examples(type: "skill" | "connector" | "connector-ui" | "solution")\`
- \`ateam_get_workflows()\` — builder workflow state machines

Read these on your first edit into an area you haven't touched.

---

${AGENT_DOC_SENTINEL}

`;
}

/**
 * Merge the newly-rendered header with an existing CLAUDE.md, preserving
 * anything below the sentinel (solution-specific notes).
 *
 * Output is deterministic so consecutive merges on the same inputs produce
 * byte-identical output (required for the idempotent-write path in
 * ateam_write_agent_doc).
 *
 * @param {string} freshHeader   - Output of renderAgentDocHeader
 * @param {string|null} existing - Current CLAUDE.md contents (or null if new file)
 * @returns {string} merged markdown
 */
export function mergeAgentDoc(freshHeader, existing) {
  // Normalize freshHeader: strip trailing whitespace, end with exactly "\n".
  // This prevents newline accumulation when the output is read back and merged again.
  const headerNormalized = freshHeader.replace(/\s+$/, "") + "\n";

  const extractNotes = (src) => {
    if (!src) return "";
    const idx = src.indexOf(AGENT_DOC_SENTINEL);
    const afterSentinel = idx === -1 ? src : src.slice(idx + AGENT_DOC_SENTINEL.length);
    return afterSentinel.trim();
  };

  const notes = extractNotes(existing);
  return notes ? `${headerNormalized}\n${notes}\n` : headerNormalized;
}

// ──────────────────────────────────────────────────────────────────────────

function oneLine(s) {
  return String(s || "").replace(/\s+/g, " ").trim().slice(0, 200);
}

function inferTenantFromId() {
  // Can't reliably infer from solution_id alone; caller can override by
  // setting tenant on the rendered header via post-processing if needed.
  return null;
}

function buildConnectorTable({ platform, solution }) {
  const rows = [];
  if (solution.length) {
    rows.push("**Solution connectors** (live in this repo under `connectors/`):");
    for (const id of solution) rows.push(`  - \`${id}\``);
    rows.push("");
  }
  if (platform.length) {
    rows.push("**Platform connectors** (shared infrastructure, not in this repo):");
    for (const id of platform) rows.push(`  - \`${id}\``);
    rows.push("");
  }
  if (!rows.length) rows.push("_(no connectors declared)_");
  return rows.join("\n");
}

function buildToolTable() {
  return [
    "| Task | Tool |",
    "|------|------|",
    // It said github_patch → build_and_run(github:true). build_and_run
    // deploys `main`, so that sequence is refused (MAIN_BEHIND_DEV) or ships
    // without the edit. Test from dev; ship with promote.
    "| Edit connector source code | `ateam_github_patch` / `ateam_github_write`, then `ateam_upload_connector(solution_id, connector_id, github:true)` to test it from `dev` |",
    "| Edit skill definition (persona, tools, intents, guardrails) | `ateam_patch(target:\"skill\", skill_id, updates)` |",
    "| Edit solution definition | `ateam_patch(target:\"solution\", updates)` |",
    "| First deploy (with `mcp_store`) / deploy `main` after a promote | `ateam_build_and_run(solution_id)` |",
    "| Run a skill end-to-end | `ateam_test_skill(solution_id, skill_id, message)` |",
    "| Call one connector tool in isolation | `ateam_test_connector(solution_id, connector_id, tool, args)` |",
    "| Inspect deployed state | `ateam_get_solution(solution_id, view: \"definition\"|\"skills\"|\"health\")` |",
    "| Read file from repo | `ateam_github_read(solution_id, path)` |",
    // promote SHIPS (dev → main); calling it "Checkpoint" is the framing
    // BRANCH_WORKFLOW.promote_is_a_ship_not_a_checkpoint retires.
    "| Ship `dev` → `main` | `ateam_github_promote(solution_id)` (`dry_run:true` first shows what would ship) |",
    "| Rollback `main` | `ateam_github_rollback(solution_id, target)`, then `ateam_github_sync_from_main(solution_id)` |",
    "| List shipped versions | `ateam_github_list_versions(solution_id)` |",
  ].join("\n");
}

function buildUniversalPitfalls() {
  return [
    "- **`ateam_test_connector` runs as `_system_service`.** Core strips user-provided `_adas_actor` when you call via the test harness. Use it for connector-level bugs; use `ateam_test_skill` / `ateam_conversation` for per-user-actor flows.",
    "- **`.ateam/export.json` is auto-generated.** Never hand-edit. Deploys read it, so stale copies silently break things.",
    "- **Prefer `ateam_patch` over `github_patch` + a deploy** for skill-definition edits. One call that writes `dev` and redeploys what it patched; check its `redeploy` phase, which reports a failed redeploy (the edit is kept).",
    "- **Always refetch dynamic ids.** Corpus ids, job ids, actor ids change. Call `docs.corpus.list` / `ateam_list_solutions` / etc. in the current job — don't reuse ids from memory or previous sessions.",
    "- **MCP tool param names are strict.** `top_k` (not `k`), `corpus_id` (not `corpus`). Passing wrong names silently fails zod validation.",
    "- **Don't count `{ok:false}` as success.** When calling one MCP from another, always check `result.ok` before incrementing a success counter.",
    "- **Connectors are stdio, not HTTP.** Use `StdioServerTransport`. Never `app.listen()`. Log with `console.error` (stdout is the JSON-RPC channel).",
    "- **Shared-tenant resources need `shared: true`.** When a resource (corpus, bind, etc.) is used across users in a tenant, pass `shared: true` at create time — otherwise per-user actor isolation blocks cross-user access.",
  ].map((s) => "- " + s.replace(/^- /, "")).join("\n");
}

function buildRepoLayout({ skills, connectors }) {
  const skillDirs = skills.map((s) => `  ${s.id}/skill.json`).join("\n") || "  _(no skills)_";
  const connDirs = connectors.length
    ? connectors.map((c) => `  ${c.id}/\n    server.js\n    package.json`).join("\n")
    : "  _(no solution connectors)_";
  return [
    "solution.json                    # full solution definition",
    "skills/",
    skillDirs,
    "connectors/                      # solution connectors (stdio MCPs)",
    connDirs,
    ".ateam/export.json               # auto-generated deploy bundle (don't hand-edit)",
    "CLAUDE.md                        # this file — auto-regenerated above sentinel",
  ].join("\n");
}
